skeleton/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Index
    url(r'^$', 'sideloader.views.index', name='home'),

    # Projects
    url(r'^projects/create$', 'sideloader.views.projects_create', name='projects_create'),
    url(r'^projects/edit/(?P<id>[\w-]+)$', 'sideloader.views.projects_edit', name='projects_edit'),
    url(r'^projects/view/(?P<id>[\w-]+)$', 'sideloader.views.projects_view', name='projects_view'),
    url(r'^projects/build/(?P<id>[\w-]+)$', 'sideloader.views.projects_build', name='projects_build'),
    url(r'^projects/delete/(?P<id>[\w-]+)$', 'sideloader.views.projects_delete', name='projects_delete'),

    url(r'^projects/build/view/(?P<id>[\w-]+)$', 'sideloader.views.build_view', name='build_view'),
    url(r'^projects/build/log/(?P<id>[\w-]+)$', 'sideloader.views.build_output', name='build_output'),
    url(r'^projects/build/cancel/(?P<id>[\w-]+)$', 'sideloader.views.build_cancel', name='build_cancel'),

    # Workflows
    url(r'^workflow/edit/(?P<id>[\w-]+)$', 'sideloader.views.workflow_edit', name='workflow_edit'),
    url(r'^workflow/delete/(?P<id>[\w-]+)$', 'sideloader.views.workflow_delete', name='workflow_delete'),
    url(r'^workflow/suck/(?P<id>[\w-]+)$', 'sideloader.views.release_delete', name='release_delete'),
    url(r'^workflow/create/(?P<project>[\w-]+)$', 'sideloader.views.workflow_create', name='workflow_create'),
    url(r'^workflow/push/(?P<flow>[\w-]+)/(?P<build>[\w-]+)$', 'sideloader.views.workflow_push', name='workflow_push'),
    url(r'^workflow/schedule/(?P<flow>[\w-]+)/(?P<build>[\w-]+)$', 'sideloader.views.workflow_schedule', name='workflow_schedule'),

    url(r'^workflow/manifests/(?P<id>[\d]+)$', 'sideloader.views.manifest_view', name='manifest_view'),
    url(r'^workflow/manifests/add/(?P<id>[\d]+)$', 'sideloader.views.manifest_add', name='manifest_add'),
    url(r'^workflow/manifests/edit/(?P<id>[\d]+)$', 'sideloader.views.manifest_edit', name='manifest_edit'),
    url(r'^workflow/manifests/delete/(?P<id>[\d]+)$', 'sideloader.views.manifest_delete', name='manifest_delete'),

    url(r'^workflow/webhooks/(?P<id>[\d]+)$', 'sideloader.views.webhooks_view', name='webhooks'),
    url(r'^workflow/webhooks/(?P<id>[\d]+)/create$', 'sideloader.views.webhooks_create', name='webhooks_create'),
    url(r'^workflow/webhooks/edit/(?P<id>[\d]+)$', 'sideloader.views.webhooks_edit', name='webhooks_edit'),
    url(r'^workflow/webhooks/delete/(?P<id>[\d]+)$', 'sideloader.views.webhooks_delete', name='webhooks_delete'),

    # Modules
    url(r'^modules/edit/(?P<id>[\w]+)$', 'sideloader.views.module_edit', name='module_edit'),
    url(r'^modules/create$', 'sideloader.views.module_create', name='module_create'),
    url(r'^modules/get_scheme/(?P<id>[\w]+)$', 'sideloader.views.module_scheme', name='module_scheme'),
    url(r'^modules/$', 'sideloader.views.module_index', name='module_index'),

    # Releases
    url(r'^releases/edit/(?P<id>[\w-]+)$', 'sideloader.views.release_edit', name='edit_release'),
    url(r'^releases/create$', 'sideloader.views.release_create', name='create_release'),
    url(r'^releases/$', 'sideloader.views.release_index', name='release_index'),

    # Servers
    url(r'^servers/$', 'sideloader.views.server_index', name='server_index'),
    url(r'^servers/log/(?P<id>[\w-]+)$', 'sideloader.views.server_log', name='server_log'),
    url(r'^servers/json/$', 'sideloader.views.get_servers', name='get_servers'),
    url(r'^servers/json/workflow/(?P<id>[\w-]+)$', 'sideloader.views.get_workflow_servers', name='get_workflow_servers'),

    # Help
    url(r'^help/$', 'sideloader.views.help_index', name='help_index'),

    # API
    url(r'^api/build/(?P<hash>[\w-]+)$', 'sideloader.views.api_build', name='api_build'),
    url(r'^api/rap/(?P<hash>[\w-]+)$', 'sideloader.views.api_sign', name='api_sign'),
    url(r'^api/checkin$', 'sideloader.views.api_checkin', name='api_checkin'),
    url(r'^api/enc/(?P<server>[\w.-]+)$', 'sideloader.views.api_enc', name='api_enc'),

    # Authentication
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),
    url(r'^accounts/profile/$', 'sideloader.views.accounts_profile', name='accounts_profile'),

    url(r'', include('social.apps.django_app.urls', namespace='social')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

sideloader/models.py
import time
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Server(models.Model):
    name = models.CharField(max_length=255)
    last_checkin = models.DateTimeField(auto_now_add=True)
    last_puppet_run = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=255, default='', blank=True)
    change = models.BooleanField(default=True)
    specter_status = models.CharField(max_length=255, default='', blank=True)

    def age(self):
        """Returns seconds since last checkin"""
        now = timezone.now()
        return int((now - self.last_checkin).total_seconds())

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.__unicode__().encode('utf-8', 'replace')


class ReleaseStream(models.Model):
    name = models.CharField(max_length=255)
    push_command = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.__unicode__().encode('utf-8', 'replace')


class Project(models.Model):
    name = models.CharField(max_length=255, unique=True)
    github_url = models.CharField(max_length=255)
    branch = models.CharField(max_length=255)
    package_manager = models.CharField(max_length=64, default='deb')
    deploy_type = models.CharField(max_length=64, default='virtualenv')
    deploy_file = models.CharField(max_length=255, default='.deploy.yaml', blank=True)
    package_name = models.CharField(max_length=255, default='', blank=True)
    build_script = models.CharField(max_length=255, default='', blank=True)
    postinstall_script = models.CharField(
        max_length=255, default='', blank=True)

    created_by_user = models.ForeignKey(User, related_name="ProjectCreatedBy")
    release_stream = models.ForeignKey(ReleaseStream, null=True)
    idhash = models.CharField(max_length=48)
    allowed_users = models.ManyToManyField(User, blank=True)
    notifications = models.BooleanField(default=True)
    slack_channel = models.CharField(max_length=255, default='', blank=True)


class BuildNumbers(models.Model):
    package = models.CharField(max_length=255, unique=True)
    build_num = models.IntegerField(default=0)


class ReleaseFlow(models.Model):
    name = models.CharField(max_length=255)
    project = models.ForeignKey(Project)
    stream_mode = models.IntegerField(default=0)
    stream = models.ForeignKey(ReleaseStream, null=True, blank=True)
    require_signoff = models.BooleanField(default=False)
    signoff_list = models.TextField(blank=True)
    quorum = models.IntegerField(default=0)
    notify = models.BooleanField(default=False)
    notify_list = models.TextField(blank=True)
    service_restart = models.BooleanField(default=True)
    service_pre_stop = models.BooleanField(default=False)
    puppet_run = models.BooleanField(default=True)
    auto_release = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.__unicode__().encode('utf-8', 'replace')

    def email_list(self):
        if not '@' in self.signoff_list:
            return []

        return self.signoff_list.replace('\r', ' ').replace(
            '\n', ' ').replace(',', ' ').strip().split()

    def last_release(self):
        rs = self.release_set.filter(waiting=False).order_by('-release_date')
        if rs:
            return rs[0]
        else:
            return None

    def next_release(self):
        rs = self.release_set.filter(waiting=True).order_by('-release_date')
        if rs:
            return rs[0]
        else:
            return None


class WebHook(models.Model):
    flow = models.ForeignKey(ReleaseFlow)
    description = models.CharField(max_length=255)
    url = models.CharField(max_length=255)
    method = models.CharField(max_length=4)
    content_type = models.CharField(max_length=255)
    payload = models.TextField(blank=True)
    after = models.ForeignKey('self', null=True, blank=True)
    last_response = models.TextField(blank=True)

    def __unicode__(self):
        return self.description

    def __str__(self):
        return self.__unicode__().encode('utf-8', 'replace')


class Build(models.Model):
    project = models.ForeignKey(Project)
    build_time = models.DateTimeField(auto_now_add=True)
    # 0 - queued, 1 - Success, 2 - Failed, 3 - Canceled
    state = models.IntegerField(default=0)
    task_id = models.CharField(max_length=255, default='')
    log = models.TextField(default="")
    build_file = models.CharField(max_length=255)


class Target(models.Model):
    server = models.ForeignKey(Server)
    release = models.ForeignKey(ReleaseFlow)
    # 0 - Nothing, 1 - In progress, 2 - Good, 3 - Bad
    deploy_state = models.IntegerField(default=0)
    current_build = models.ForeignKey(Build, null=True, blank=True)
    log = models.TextField(default="")


class ModuleManifest(models.Model):
    name = models.CharField(max_length=255)
    key = models.CharField(max_length=255)
    structure = models.TextField()

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.__unicode__().encode('utf-8', 'replace')


class ServerManifest(models.Model):
    module = models.ForeignKey(ModuleManifest)
    value = models.TextField()
    release = models.ForeignKey(ReleaseFlow)

    def __unicode__(self):
        return self.module.name

    def __str__(self):
        return self.__unicode__().encode('utf-8', 'replace')


class Release(models.Model):
    release_date = models.DateTimeField(auto_now_add=True)
    flow = models.ForeignKey(ReleaseFlow)
    build = models.ForeignKey(Build)
    scheduled = models.DateTimeField(blank=True, null=True)
    waiting = models.BooleanField(default=True)
    lock = models.BooleanField(default=False)

    def signoff_count(self):
        return self.releasesignoff_set.filter(signed=True).count()

    def signoff_remaining(self):
        q = self.flow.quorum
        if q == 0:
            return len(self.flow.email_list()) - self.signoff_count()
        return self.flow.quorum - self.signoff_count()

    def check_signoff(self):
        if not self.flow.require_signoff:
            return True

        if self.signoff_remaining()>0:
            return False

        return True

    def check_schedule(self):
        if not self.scheduled:
            return True

        t = int(time.mktime(self.scheduled.timetuple()))
        if (time.time() - t) > 0:
            return True
        return False

    def release_state(self):
        if self.waiting:
            if self.flow.require_signoff:
                # Sign-offs required
                remaining = self.signoff_remaining()
                if (remaining > 0):
                    return (3, remaining)

            if self.check_schedule():
                return (4, None)
            return (2, self.scheduled)
        else:
            return (1, None)

    def get_state(self):
        c, s = self.release_state()

        messages = {
            1: lambda t: "Deployed",
            2: lambda t: "Scheduled for %s (UTC)" % t.strftime("%d-%m-%Y @ %H:%M"),
            3: lambda t: "Waiting for %s signature%s" % (t, t>1 and 's' or ''),
            4: lambda t: "Running..."
        }
        
        return messages[c](s)

    def __repr__(self):
        return "<Release(release_date=%s, flow=%s, build=%s, scheduled=%s, waiting=%s, lock=%s)>" % (
            self.release_date, self.flow.id, self.build.id, self.scheduled,
            self.waiting, self.lock
        )


class ReleaseSignoff(models.Model):
    release = models.ForeignKey(Release)
    signature = models.CharField(max_length=255)
    idhash = models.CharField(max_length=48)
    signed = models.BooleanField(default=False)

sideloader/templates/flows/create_edit.html
{% extends "fragments/default.html" %}
{% load crispy_forms_tags %}
{% block navbar %}
{% include "fragments/navbar.html" %}
{% endblock %}

{% block head %}
<link href="/static/css/select2.css" rel="stylesheet"/>
<link href="/static/css/select2-bootstrap.css" rel="stylesheet"/>
{% endblock %}

{% block content %}
<div class="col-lg-9" id="formcontainer">
    <h4 style="margin-bottom:10px">{% if workflow %}Edit workflow{% else %}Create workflow{% endif %}</h4>
    {% crispy form %}

</div>
{% endblock %}

{% block script %}
<script src="/static/js/select2.min.js"></script>
<script>
    $(function () {
        $("#id_targets").select2({
            width: "resolve",
            placeholder: "Select servers",
            allowClear: true
        })

        var signoff = true;

        function toggleSignoff(){
            var signoff = !$("#id_require_signoff")[0].checked;
            if (signoff) {
                $("#div_id_signoff_list").hide();
                $("#div_id_quorum").hide();
            }
            else {
                $("#div_id_signoff_list").show();
                $("#div_id_quorum").show();
            }
        }

        var notify = true;

        function toggleNotify(){
            var signoff = !$("#id_notify")[0].checked;
            if (signoff) {
                $("#div_id_notify_list").hide();
            }
            else {
                $("#div_id_notify_list").show();
            }
        }

        function toggleMode(){
            var mode = $('input:radio[name=stream_mode]:checked').val();

            if (mode==1) {
                // Server
                $("#div_id_stream").hide();
                $("#div_id_targets").show();

                $("#div_id_puppet_run").show();
                $("#div_id_service_restart").show();
                $("#div_id_service_pre_stop").show();
            }
            else if (mode==0){
                // Stream
                $("#div_id_stream").show();
                $("#div_id_targets").hide();
                $("#div_id_puppet_run").hide();
                $("#div_id_service_restart").hide();
                $("#div_id_service_pre_stop").hide();
            }
            else if (mode==2){
                // Both
                $("#div_id_stream").show();
                $("#div_id_targets").show();

                $("#div_id_puppet_run").show();
                $("#div_id_service_restart").show();
                $("#div_id_service_pre_stop").show();
            }
        }

        $("#id_require_signoff").click(toggleSignoff);
        toggleSignoff();
        
        $("#id_notify").click(toggleNotify);
        toggleNotify();

        $('input:radio[name=stream_mode]').change(toggleMode);
        toggleMode();
    });
</script>
{% endblock %}

sideloader/templates/flows/schedule.html
{% extends "fragments/default.html" %}
{% block navbar %}
{% include "fragments/navbar.html" %}
{% endblock %}

{% block head %}
<link href="/static/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="col-lg-9">
    <h4 style="margin-bottom:10px">Push build `{{build.build_file}}` to {{flow.name}}</h4>
    <br/>
    <br/>

    <form class="form-horizontal" method="post" >
        {% csrf_token %}
        <input type='hidden' name='tz' id='tz' value='' />

        <div id="div_id_scheduled" class="form-group">
            <label for="id_scheduled" class="control-label col-lg-2 requiredField">Schedule release</label>
            <div class="col-lg-5 controls">
                <div class="form-group">
                  <div id="datetimepicker1" data-date-format="YYYY-MM-DD hh:mm" class="input-group date">
                    <input type="text" id="id_scheduled" class="form-control" name="scheduled"></input>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                  </div>
                </div>
            </div>
        </div>
            
        <div class="form-actions">
            <input type="submit" name="submit" value="Submit" class="btn btn-primary" id="submit-id-submit"/>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/js/moment.js"></script> 
<script type="text/javascript" src="/static/js/bootstrap-datetimepicker.min.js"></script> 
<script type="text/javascript">
  $(function() {
    $('#datetimepicker1').datetimepicker();

    var d = new Date()
    var n = d.getTimezoneOffset()/60;

    $('#tz').val(parseInt(n));

  });
</script>

{% endblock %}

sideloader/templates/flows/webhooks_create_edit.html
{% extends "fragments/default.html" %}
{% load crispy_forms_tags %}
{% block navbar %}
{% include "fragments/navbar.html" %}
{% endblock %}

{% block head %}
<link href="/static/css/select2.css" rel="stylesheet"/>
<link href="/static/css/select2-bootstrap.css" rel="stylesheet"/>
{% endblock %}

{% block content %}
<div class="col-lg-9" id="formcontainer">
    <h4 style="margin-bottom:10px">{% if webhook %}Edit webhook{% else %}Add webhook{% endif %}</h4>
    {% crispy form %}

</div>
{% endblock %}

{% block script %}
<script src="/static/js/select2.min.js"></script>
<script>
    $(function () {

        function togglePayload(){
            var method = $("#id_method").val();

            console.log(method);

            if (method=="POST") {
                $("#div_id_payload").show();
            }
            else {
                $("#div_id_payload").hide();
            }
        }
                
        $('#id_method').change(togglePayload);
        togglePayload();
    });
</script>
{% endblock %}

sideloader/templates/flows/webhooks_view.html
{% extends "fragments/default.html" %}
{% block navbar %}
{% include "fragments/navbar.html" with active="releases" %}
{% endblock %}

{% block content %}

<div class="col-lg-9">
    <h4>{{project.name}} {{release.name}} Webhooks</h4>
    <p>
        {% if user.is_superuser %}
        <a href="{% url 'webhooks_create' id=release.id %}" class="btn btn-default">Create new</a>
        {% endif %}
        {% if webhooks %}
        <table class="table table-hover table-bordered table-condensed">
          <thead>
            <tr>
              <th>Description</th><th>URL</th><th>Method</th><th>Parent</th><th></th>
            </tr>
          </thead>
          <tbody>
            {% for webhook in webhooks %}
            <tr>
              <td>{{ webhook.description }}</td>
              <td>{{ webhook.url }}</td>
              <td>{{ webhook.method }}</td>
              <td>{{ webhook.after.description }}</td>
              <td width="90em">
                <div class="btn-group btn-group-sm">
                  <a class="btn btn-default" href="{% url 'webhooks_edit' id=webhook.id %}" title="Edit"><span class="glyphicon glyphicon-edit electric"></span></a>
                  <a class="btn btn-default" href="{% url 'webhooks_delete' id=webhook.id %}" title="Delete"><span class="glyphicon glyphicon-remove electric"></span></a>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <br/><br/>
        No releases configured
        {% endif %}
    </p>
</div>

{% endblock %}